
name: 'my_template_models'
version: '1.0.0'
config-version: 2

model-paths: ["templates"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  my_template_models:
    +enabled: false